### 405 Method Not Allowed
GET http://localhost:8080/muxer

### 404 Bad Request
POST http://localhost:8080/muxer

### 200 OK
POST http://localhost:8080/muxer
Content-Type: application/json

{"urls": [
  "https://jsonplaceholder.typicode.com/posts"
]}
